### ISSUE TITLE
我服务器都没部署好 怎么能发送评论呢？

### ISSUE THREAD

**Issue by jj89757hhb** [SimleCp/BBS-iOS#1]

**Comment by zedxpp** [comment]
[https://github.com/zedxpp/BBS](https://github.com/zedxpp/BBS)

iOS端的请求地址配置文件在`BBS-iOS/Tool.swift`

默认是 `let httpAdress = "http://swift520.com:8181/"` 也就是我的服务器.  所以你能评论.

**Comment by jj89757hhb** [comment]
哦 难怪
